name: My GitHub Actions Workflow

on:
  push:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.17.0

      - name: Print Node.js version
        run: |
          node --version

      - name: Make Bash script executable
        run: |
          chmod +x test.sh

      - name: Run Bash script
        run: |
          ./test.sh
